eureka:
  client:
    service-url:
      default-zone: http://localhost:8762/eureka/

spring:
  data:
    mongodb:
      uri: mongodb+srv://taskapp:root@cluster0.xqmxd.mongodb.net/orderdb
      port: 27017
      authentication-database: admin
